
import { KanaCharacter } from './types';

export const HIRAGANA_DATA: KanaCharacter[] = [
  // Basic
  { char: 'あ', romaji: 'a', thai: 'อะ', type: 'basic', category: 'hiragana' },
  { char: 'い', romaji: 'i', thai: 'อิ', type: 'basic', category: 'hiragana' },
  { char: 'う', romaji: 'u', thai: 'อุ', type: 'basic', category: 'hiragana' },
  { char: 'え', romaji: 'e', thai: 'เอะ', type: 'basic', category: 'hiragana' },
  { char: 'お', romaji: 'o', thai: 'โอะ', type: 'basic', category: 'hiragana' },
  { char: 'か', romaji: 'ka', thai: 'คะ', type: 'basic', category: 'hiragana' },
  { char: 'き', romaji: 'ki', thai: 'คิ', type: 'basic', category: 'hiragana' },
  { char: 'く', romaji: 'ku', thai: 'คุ', type: 'basic', category: 'hiragana' },
  { char: 'け', romaji: 'ke', thai: 'เคะ', type: 'basic', category: 'hiragana' },
  { char: 'こ', romaji: 'ko', thai: 'โคะ', type: 'basic', category: 'hiragana' },
  { char: 'さ', romaji: 'sa', thai: 'สะ', type: 'basic', category: 'hiragana' },
  { char: 'し', romaji: 'shi', thai: 'ชิ', type: 'basic', category: 'hiragana' },
  { char: 'す', romaji: 'su', thai: 'สุ', type: 'basic', category: 'hiragana' },
  { char: 'せ', romaji: 'se', thai: 'เซะ', type: 'basic', category: 'hiragana' },
  { char: 'そ', romaji: 'so', thai: 'โซะ', type: 'basic', category: 'hiragana' },
  { char: 'た', romaji: 'ta', thai: 'ทะ', type: 'basic', category: 'hiragana' },
  { char: 'ち', romaji: 'chi', thai: 'ชิ', type: 'basic', category: 'hiragana' },
  { char: 'つ', romaji: 'tsu', thai: 'สึ', type: 'basic', category: 'hiragana' },
  { char: 'て', romaji: 'te', thai: 'เทะ', type: 'basic', category: 'hiragana' },
  { char: 'と', romaji: 'to', thai: 'โทะ', type: 'basic', category: 'hiragana' },
  { char: 'な', romaji: 'na', thai: 'นะ', type: 'basic', category: 'hiragana' },
  { char: 'に', romaji: 'ni', thai: 'นิ', type: 'basic', category: 'hiragana' },
  { char: 'ぬ', romaji: 'nu', thai: 'นุ', type: 'basic', category: 'hiragana' },
  { char: 'ね', romaji: 'ne', thai: 'เนะ', type: 'basic', category: 'hiragana' },
  { char: 'の', romaji: 'no', thai: 'โนะ', type: 'basic', category: 'hiragana' },
  { char: 'は', romaji: 'ha', thai: 'ฮะ', type: 'basic', category: 'hiragana' },
  { char: 'ひ', romaji: 'hi', thai: 'ฮิ', type: 'basic', category: 'hiragana' },
  { char: 'ふ', romaji: 'fu', thai: 'ฟุ', type: 'basic', category: 'hiragana' },
  { char: 'へ', romaji: 'he', thai: 'เฮะ', type: 'basic', category: 'hiragana' },
  { char: 'ほ', romaji: 'ho', thai: 'โฮะ', type: 'basic', category: 'hiragana' },
  { char: 'ま', romaji: 'ma', thai: 'มะ', type: 'basic', category: 'hiragana' },
  { char: 'み', romaji: 'mi', thai: 'มิ', type: 'basic', category: 'hiragana' },
  { char: 'む', romaji: 'mu', thai: 'มุ', type: 'basic', category: 'hiragana' },
  { char: 'め', romaji: 'me', thai: 'เมะ', type: 'basic', category: 'hiragana' },
  { char: 'も', romaji: 'mo', thai: 'โมะ', type: 'basic', category: 'hiragana' },
  { char: 'や', romaji: 'ya', thai: 'ยะ', type: 'basic', category: 'hiragana' },
  { char: 'ゆ', romaji: 'yu', thai: 'ยุ', type: 'basic', category: 'hiragana' },
  { char: 'よ', romaji: 'yo', thai: 'โยะ', type: 'basic', category: 'hiragana' },
  { char: 'ら', romaji: 'ra', thai: 'ระ', type: 'basic', category: 'hiragana' },
  { char: 'り', romaji: 'ri', thai: 'ริ', type: 'basic', category: 'hiragana' },
  { char: 'る', romaji: 'ru', thai: 'รุ', type: 'basic', category: 'hiragana' },
  { char: 'れ', romaji: 're', thai: 'เระ', type: 'basic', category: 'hiragana' },
  { char: 'ろ', romaji: 'ro', thai: 'โระ', type: 'basic', category: 'hiragana' },
  { char: 'わ', romaji: 'wa', thai: 'วะ', type: 'basic', category: 'hiragana' },
  { char: 'を', romaji: 'wo', thai: 'โวะ', type: 'basic', category: 'hiragana' },
  { char: 'ん', romaji: 'n', thai: 'อึน', type: 'basic', category: 'hiragana' },
  // Dakuon
  { char: 'が', romaji: 'ga', thai: 'กะ', type: 'dakuon', category: 'hiragana' },
  { char: 'ぎ', romaji: 'gi', thai: 'กิ', type: 'dakuon', category: 'hiragana' },
  { char: 'ぐ', romaji: 'gu', thai: 'กุ', type: 'dakuon', category: 'hiragana' },
  { char: 'げ', romaji: 'ge', thai: 'เกะ', type: 'dakuon', category: 'hiragana' },
  { char: 'ご', romaji: 'go', thai: 'โกะ', type: 'dakuon', category: 'hiragana' },
];

export const KATAKANA_DATA: KanaCharacter[] = [
  { char: 'ア', romaji: 'a', thai: 'อะ', type: 'basic', category: 'katakana' },
  { char: 'イ', romaji: 'i', thai: 'อิ', type: 'basic', category: 'katakana' },
  { char: 'ウ', romaji: 'u', thai: 'อุ', type: 'basic', category: 'katakana' },
  { char: 'エ', romaji: 'e', thai: 'เอะ', type: 'basic', category: 'katakana' },
  { char: 'オ', romaji: 'o', thai: 'โอะ', type: 'basic', category: 'katakana' },
  { char: 'カ', romaji: 'ka', thai: 'คะ', type: 'basic', category: 'katakana' },
  { char: 'キ', romaji: 'ki', thai: 'คิ', type: 'basic', category: 'katakana' },
  { char: 'ク', romaji: 'ku', thai: 'คุ', type: 'basic', category: 'katakana' },
  { char: 'ケ', romaji: 'ke', thai: 'เคะ', type: 'basic', category: 'katakana' },
  { char: 'コ', romaji: 'ko', thai: 'โคะ', type: 'basic', category: 'katakana' },
  { char: 'サ', romaji: 'sa', thai: 'สะ', type: 'basic', category: 'katakana' },
  { char: 'シ', romaji: 'shi', thai: 'ชิ', type: 'basic', category: 'katakana' },
  { char: 'ス', romaji: 'su', thai: 'สุ', type: 'basic', category: 'katakana' },
  { char: 'セ', romaji: 'se', thai: 'เซะ', type: 'basic', category: 'katakana' },
  { char: 'ソ', romaji: 'so', thai: 'โซะ', type: 'basic', category: 'katakana' },
  { char: 'タ', romaji: 'ta', thai: 'ทะ', type: 'basic', category: 'katakana' },
  { char: 'チ', romaji: 'chi', thai: 'ชิ', type: 'basic', category: 'katakana' },
  { char: 'ツ', romaji: 'tsu', thai: 'สึ', type: 'basic', category: 'katakana' },
  { char: 'テ', romaji: 'te', thai: 'เทะ', type: 'basic', category: 'katakana' },
  { char: 'ト', romaji: 'to', thai: 'โทะ', type: 'basic', category: 'katakana' },
  { char: 'ナ', romaji: 'na', thai: 'นะ', type: 'basic', category: 'katakana' },
  { char: 'ニ', romaji: 'ni', thai: 'นิ', type: 'basic', category: 'katakana' },
  { char: 'ヌ', romaji: 'nu', thai: 'นุ', type: 'basic', category: 'katakana' },
  { char: 'ネ', romaji: 'ne', thai: 'เนะ', type: 'basic', category: 'katakana' },
  { char: 'ノ', romaji: 'no', thai: 'โนะ', type: 'basic', category: 'katakana' },
  { char: 'ハ', romaji: 'ha', thai: 'ฮะ', type: 'basic', category: 'katakana' },
  { char: 'ヒ', romaji: 'hi', thai: 'ฮิ', type: 'basic', category: 'katakana' },
  { char: 'フ', romaji: 'fu', thai: 'ฟุ', type: 'basic', category: 'katakana' },
  { char: 'ヘ', romaji: 'he', thai: 'เฮะ', type: 'basic', category: 'katakana' },
  { char: 'ホ', romaji: 'ho', thai: 'โฮะ', type: 'basic', category: 'katakana' },
  { char: 'マ', romaji: 'ma', thai: 'มะ', type: 'basic', category: 'katakana' },
  { char: 'ミ', romaji: 'mi', thai: 'มิ', type: 'basic', category: 'katakana' },
  { char: 'ム', romaji: 'mu', thai: 'มุ', type: 'basic', category: 'katakana' },
  { char: 'メ', romaji: 'me', thai: 'เมะ', type: 'basic', category: 'katakana' },
  { char: 'モ', romaji: 'mo', thai: 'โมะ', type: 'basic', category: 'katakana' },
  { char: 'ヤ', romaji: 'ya', thai: 'ยะ', type: 'basic', category: 'katakana' },
  { char: 'ユ', romaji: 'yu', thai: 'ยุ', type: 'basic', category: 'katakana' },
  { char: 'ヨ', romaji: 'yo', thai: 'โยะ', type: 'basic', category: 'katakana' },
  { char: 'ラ', romaji: 'ra', thai: 'ระ', type: 'basic', category: 'katakana' },
  { char: 'リ', romaji: 'ri', thai: 'ริ', type: 'basic', category: 'katakana' },
  { char: 'ル', romaji: 'ru', thai: 'รุ', type: 'basic', category: 'katakana' },
  { char: 'レ', romaji: 're', thai: 'เระ', type: 'basic', category: 'katakana' },
  { char: 'ロ', romaji: 'ro', thai: 'โระ', type: 'basic', category: 'katakana' },
  { char: 'ワ', romaji: 'wa', thai: 'วะ', type: 'basic', category: 'katakana' },
  { char: 'ヲ', romaji: 'wo', thai: 'โวะ', type: 'basic', category: 'katakana' },
  { char: 'ン', romaji: 'n', thai: 'อึน', type: 'basic', category: 'katakana' },
];
